- name: Top Gun
  rating: 8.5/10
  action: Action
  drama: Drama
  year: 2021
  image: image/Top_Gun.jpg
- name: Jungle Cruise
  rating: 7.9/10
  action: Adventure
  drama: Fantasy
  year: 2022
  image: image/jungle.jpeg
- name: Avatar
  rating: 9.2/10
  action: Sci-Fi
  drama: Mystery
  year: 2023
  image: image/avatar.jpeg
- name: Scream
  rating: 6.8/10
  action: Suspense
  drama: Mystery
  year: 2024
  image: image/scream.jpg
- name: Anabella
  rating: 8.0/10
  action: Thriller
  drama: Horror
  year: 2025
  image: image/anabella.jpg

